### PR TITLE
fix: removed unnecessary strict post number checking causing error

### LINKED ISSUE #867: Some API responses are `text/plain`, rather than JSON
While writing some tests for my library, I stumbled upon another minor inconsistency: trying to retrieve a non-existent post will *always* return a response in `text/plain`, whether authenticated or not.

Reproduction:

```
❯ curl -i http://localhost:8080/api/posts/0 -H "content-type: application/json"
HTTP/1.1 404 Not Found
Cache-Control: public, max-age=604800, immutable
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 09 Nov 2023 18:19:02 GMT
Content-Length: 19

404 page not found
```

Same thing happens when I try to post an update, or delete a non-existing post: the response is in text/plain. Looks like the entire `/api/posts/{id}` endpoint returns text/plain when the id doesn't exist, rather than the usual json.

### PR DESCRIPTION
**Pull request by Anish-Parkhi**
Remove the unnecessary strict checking of post number to be 10 char long
This was causing errors for the non-existing posts to return text/plain response

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

closes #867

### CODE REVIEW

File: routes.go [hunk 1]
```diff
@@ -159,7 +159,7 @@ func InitRoutes(apper Apper, r *mux.Router) *mux.Router {
 	// Handle posts
 	write.HandleFunc("/api/posts", handler.All(newPost)).Methods("POST")
 	posts := write.PathPrefix("/api/posts/").Subrouter()
-	posts.HandleFunc("/{post:[a-zA-Z0-9]{10}}", handler.AllReader(fetchPost)).Methods("GET")
+	posts.HandleFunc("/{post:[a-zA-Z0-9]}", handler.AllReader(fetchPost)).Methods("GET")
 	posts.HandleFunc("/{post:[a-zA-Z0-9]{10}}", handler.All(existingPost)).Methods("POST", "PUT")
 	posts.HandleFunc("/{post:[a-zA-Z0-9]{10}}", handler.All(deletePost)).Methods("DELETE")
 	posts.HandleFunc("/{post:[a-zA-Z0-9]{10}}/{property}", handler.AllReader(fetchPostProperty)).Methods("GET")
```
Comment (thebaer) [inline routes.go:165]: We should remove the `{10}` restriction on these endpoints as well, since it's resulting in the same `text/plain` response bug.

**Review by thebaer — CHANGES_REQUESTED** [review]
Thanks for taking a look at this! We just need to remove the restriction on all endpoints to fully fix this bug.

**Review by thebaer — APPROVED** [review]

**Comment by thebaer** [comment]
The previous fix actually limited this endpoint to working on posts with one-character IDs (which don't exist). I went ahead and fixed that, and will get this merged soon.
